### ISSUE TITLE
These are awesome; are they official? 

### ISSUE THREAD

**Issue by HobokenMartha** [GSA/logo#3]
Just curious about who is signing off on them.

**Comment by gbinal** [comment]
Hey @HobokenMartha - thanks.  

We actually are building off of the [great work](https://github.com/kinlane/federal-government) of @kinlane.  The data.gov team here at GSA has been improving the collection since.  Agencies often reach out with updates and we consider this an official project but this is not meant to be a canonical but it's not intended to be a canonical source.

**Comment by HobokenMartha** [comment]
Cool.  Might I recommend that you say that in the Readme?

On Wed, Mar 18, 2015 at 12:05 PM, Gray Brooks <notifications@github.com>
wrote:

> Hey @HobokenMartha <https://github.com/HobokenMartha> - thanks.
>
> We actually are building off of the great work
> <https://github.com/kinlane/federal-government> of @kinlane
> <https://github.com/kinlane>. The data.gov team here at GSA has been
> improving the collection since. Agencies often reach out with updates and
> we consider this an official project but this is not meant to be a
> canonical but it's not intended to be a canonical source.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GSA/logo/issues/3#issuecomment-83035901>.
>



-- 
Martha Garvey Jr.
Writer/Editor/Digital Strategy
http://about.me/martha_garvey
http://www.linkedin.com/in/marthagarvey
Instagram/Twitter: @hobokenmartha
